game_info['levels']['test'] = {
    'buttons': [
        {
            'x':    0,
            'y':    0,
            'size': 1,
            'name': 'jump',
        },
    ],
    'objects': [
        {
            'x':     112,
            'y':     98,
            'name':  'player',
            'extra': {},
        },
        {
            'x':     0,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     0,
            'y':     208,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     16,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     32,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     48,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     64,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     80,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     96,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     112,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     176,
            'y':     208,
            'name':  'slope',
            'extra': {'dir': 'slight right bottom'},
        },
        {
            'x':     192,
            'y':     200,
            'name':  'slope',
            'extra': {'dir': 'slight right bottom'},
        },
        {
            'x':     208,
            'y':     192,
            'name':  'slope',
            'extra': {'dir': 'right bottom'},
        },
        {
            'x':     224,
            'y':     176,
            'name':  'slope',
            'extra': {'dir': 'steep right bottom'},
        },
        {
            'x':     232,
            'y':     160,
            'name':  'slope',
            'extra': {'dir': 'steep right bottom'},
        },
        {
            'x':     240,
            'y':     128,
            'name':  'block',
            'extra': {'height': 2},
        },
        {
            'x':     232,
            'y':     112,
            'name':  'slope',
            'extra': {'dir': 'steep right top'},
        },
        {
            'x':     224,
            'y':     96,
            'name':  'slope',
            'extra': {'dir': 'steep right top'},
        },
        {
            'x':     208,
            'y':     80,
            'name':  'slope',
            'extra': {'dir': 'right top'},
        },
        {
            'x':     192,
            'y':     72,
            'name':  'slope',
            'extra': {'dir': 'slight right top'},
        },
        {
            'x':     176,
            'y':     64,
            'name':  'slope',
            'extra': {'dir': 'slight right top'},
        },
        {
            'x':     160,
            'y':     48,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     144,
            'y':     48,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     128,
            'y':     64,
            'name':  'slope',
            'extra': {'dir': 'slight left top'},
        },
        {
            'x':     112,
            'y':     72,
            'name':  'slope',
            'extra': {'dir': 'slight left top'},
        },
        {
            'x':     96,
            'y':     80,
            'name':  'slope',
            'extra': {'dir': 'left top'},
        },
        {
            'x':     80,
            'y':     96,
            'name':  'slope',
            'extra': {'dir': 'steep left top'},
        },
        {
            'x':     72,
            'y':     112,
            'name':  'slope',
            'extra': {'dir': 'steep left top'},
        },
        {
            'x':     128,
            'y':     208,
            'name':  'slope',
            'extra': {'dir': 'slight left bottom'},
        },
        {
            'x':     112,
            'y':     200,
            'name':  'slope',
            'extra': {'dir': 'slight left bottom'},
        },
        {
            'x':     96,
            'y':     192,
            'name':  'slope',
            'extra': {'dir': 'left bottom'},
        },
        {
            'x':     80,
            'y':     176,
            'name':  'slope',
            'extra': {'dir': 'steep left bottom'},
        },
        {
            'x':     72,
            'y':     160,
            'name':  'slope',
            'extra': {'dir': 'steep left bottom'},
        },
        {
            'x':     64,
            'y':     128,
            'name':  'block',
            'extra': {'height': 2},
        },
        {
            'x':     128,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     144,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     160,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     176,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     192,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     224,
            'y':     208,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     256,
            'y':     208,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     288,
            'y':     208,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     304,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     400,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     500,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     600,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     700,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     800,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     900,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     1000,
            'y':     224,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     0,
            'y':     500,
            'name':  'block',
            'extra': {},
        },
        {
            'x':     0,
            'y':     1000,
            'name':  'block',
            'extra': {},
        },
    ],
};